const now = Date.now();
const h = (hours) => new Date(now - hours * 3600000).toISOString();
const hf = (hours) => new Date(now + hours * 3600000).toISOString();

export const MOCK_TECHNICIANS = [
  { _id: 'tech1', name: 'John Mugisha', email: 'j.mugisha@mak.ac.ug', trade: 'Plumbing', zone: 'Zone A' },
  { _id: 'tech2', name: 'Peter Ssemwanga', email: 'p.ssemwanga@mak.ac.ug', trade: 'Plumbing', zone: 'Zone B' },
  { _id: 'tech3', name: 'Grace Namukasa', email: 'g.namukasa@mak.ac.ug', trade: 'Electrical', zone: 'Zone A' },
  { _id: 'tech4', name: 'David Ochieng', email: 'd.ochieng@mak.ac.ug', trade: 'Electrical', zone: 'Zone C' },
  { _id: 'tech5', name: 'Ruth Apio', email: 'r.apio@mak.ac.ug', trade: 'Carpentry', zone: 'Zone B' },
  { _id: 'tech6', name: 'Moses Tumwine', email: 'm.tumwine@mak.ac.ug', trade: 'General', zone: 'Zone D' },
];

export const MOCK_COMPLAINTS = [
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d0',
    complaintId: 'CMP-001',
    title: 'Burst water pipe flooding basement',
    description:
      'Major water pipe burst in the basement of Mitchell Hall causing flooding. Water is approximately 2 inches deep and rising rapidly. Several server racks and electrical panels are at risk.',
    location: 'Mitchell Hall, Basement Level',
    category: 'Plumbing',
    urgency: 'Critical',
    priority: 'CRITICAL',
    status: 'scope_defined',
    slaDeadline: h(-2),
    scopeDefinition: {
      description:
        'Emergency pipe repair and complete water extraction required. Inspect and repair main water line connections. Assess and document damage to electrical infrastructure.',
      estimatedDuration: 3,
      requiredSkills: ['Plumbing', 'Water Extraction', 'Electrical Safety'],
      estimatedCost: 2500000,
    },
    tasks: [
      {
        _id: 't1a',
        title: 'Emergency water shutoff',
        description: 'Locate and shut off the main water supply valve to Mitchell Hall.',
        status: 'done',
        priority: 'CRITICAL',
        estimatedDurationDays: 0.25,
        startDate: h(5),
        deadline: h(4),
        completedAt: h(4.5),
        assigneeId: 'tech1',
        assigneeName: 'John Mugisha',
        assignedAt: h(5),
        notes: 'Main valve is located in the utility room B-02.',
        createdAt: h(6),
      },
      {
        _id: 't1b',
        title: 'Flood water extraction',
        description: 'Deploy industrial pumps and extract all standing water from basement.',
        status: 'in_progress',
        priority: 'HIGH',
        estimatedDurationDays: 1,
        startDate: h(3),
        deadline: hf(21),
        completedAt: null,
        assigneeId: 'tech2',
        assigneeName: 'Peter Ssemwanga',
        assignedAt: h(3),
        notes: null,
        createdAt: h(6),
      },
      {
        _id: 't1c',
        title: 'Pipe repair and pressure test',
        description: 'Repair the burst section of the main water line and perform pressure tests.',
        status: 'open',
        priority: 'HIGH',
        estimatedDurationDays: 1.75,
        startDate: hf(22),
        deadline: hf(64),
        completedAt: null,
        assigneeId: null,
        assigneeName: null,
        assignedAt: null,
        notes: null,
        createdAt: h(6),
      },
    ],
    user: { name: 'Dr. Sarah Nakato', email: 'nakato@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Dr. Sarah Nakato', at: h(6), note: 'Complaint submitted' },
      { action: 'validated', from: 'pending', to: 'analyzed', byName: 'Estates Officer', at: h(5.5), note: 'Verified on-site' },
      { action: 'scope_defined', from: 'analyzed', to: 'scope_defined', byName: 'Estates Officer', at: h(5), note: 'Scope defined for emergency repairs' },
    ],
    createdAt: h(6),
    updatedAt: h(3),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d1',
    complaintId: 'CMP-002',
    title: 'Faulty electrical wiring in lecture theatre',
    description:
      'Exposed wiring detected behind the projector screen in LT-3. Sparks observed during evening session. Students evacuated. Fire warden report attached.',
    location: 'Main Arts Block, Lecture Theatre 3',
    category: 'Electrical',
    urgency: 'High',
    priority: 'HIGH',
    status: 'assigned',
    slaDeadline: hf(6),
    scopeDefinition: {
      description:
        'Full inspection of electrical wiring in LT-3 projector bay. Replace damaged conduit sections and test all circuits. Inspect adjacent rooms as precaution.',
      estimatedDuration: 2,
      requiredSkills: ['Electrical', 'Safety Inspection'],
      estimatedCost: 850000,
    },
    assignment: {
      technicianId: 'tech3',
      technicianName: 'Grace Namukasa',
      assignedAt: h(1),
      confirmed: true,
    },
    tasks: [
      {
        _id: 't2a',
        title: 'Isolate and make safe',
        description: 'Cut power to affected circuits and make area electrically safe.',
        status: 'done',
        priority: 'CRITICAL',
        estimatedDurationDays: 0.5,
        startDate: h(2),
        deadline: h(1.5),
        completedAt: h(1.8),
        assigneeId: 'tech3',
        assigneeName: 'Grace Namukasa',
        assignedAt: h(2),
        notes: 'Circuits 14-B and 14-C isolated.',
        createdAt: h(3),
      },
      {
        _id: 't2b',
        title: 'Rewire projector bay conduit',
        description: 'Replace 8m of damaged conduit and pull new 4mm twin-and-earth cable.',
        status: 'in_progress',
        priority: 'HIGH',
        estimatedDurationDays: 1,
        startDate: h(1),
        deadline: hf(23),
        completedAt: null,
        assigneeId: 'tech3',
        assigneeName: 'Grace Namukasa',
        assignedAt: h(1),
        notes: null,
        createdAt: h(3),
      },
      {
        _id: 't2c',
        title: 'Final inspection and circuit test',
        description: 'RCD test, insulation resistance test, and sign off compliance certificate.',
        status: 'open',
        priority: 'MEDIUM',
        estimatedDurationDays: 0.5,
        startDate: hf(24),
        deadline: hf(36),
        completedAt: null,
        assigneeId: 'tech4',
        assigneeName: 'David Ochieng',
        assignedAt: h(1),
        notes: null,
        createdAt: h(3),
      },
    ],
    user: { name: 'Prof. James Omungu', email: 'omungu@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Prof. James Omungu', at: h(8), note: 'Complaint submitted' },
      { action: 'validated', from: 'pending', to: 'analyzed', byName: 'Estates Officer', at: h(4), note: 'On-site inspection confirmed' },
      { action: 'triaged', from: 'analyzed', to: 'triaged', byName: 'Estates Officer', at: h(3.5), note: 'Priority: HIGH. SLA: 2 days' },
      { action: 'scope_defined', from: 'triaged', to: 'scope_defined', byName: 'Estates Officer', at: h(3), note: 'Scope defined' },
      { action: 'assigned', from: 'scope_defined', to: 'assigned', byName: 'Estates Officer', at: h(1), note: 'Assigned to Grace Namukasa' },
    ],
    createdAt: h(8),
    updatedAt: h(1),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d2',
    complaintId: 'CMP-003',
    title: 'Blocked drainage in student hostel Block D',
    description:
      'Main drainage channel serving floors 1-3 of Block D is completely blocked. Sewage backflow into communal bathrooms. Approximately 120 students affected.',
    location: 'University Hall, Block D, Floors 1–3',
    category: 'Plumbing',
    urgency: 'High',
    priority: 'HIGH',
    status: 'triaged',
    slaDeadline: hf(14),
    tasks: [],
    user: { name: 'Warden Beatrice Nalwanga', email: 'b.nalwanga@mak.ac.ug', role: 'warden' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Warden Beatrice Nalwanga', at: h(10), note: 'Complaint submitted' },
      { action: 'triaged', from: 'pending', to: 'triaged', byName: 'Estates Officer', at: h(9), note: 'Priority: HIGH. SLA: 2 days' },
    ],
    createdAt: h(10),
    updatedAt: h(9),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d3',
    complaintId: 'CMP-004',
    title: 'Broken windows — security risk',
    description:
      'Three windows in the ground floor of the College of Computing are broken. Glass shards on floor. Poses security and safety hazard especially at night.',
    location: 'CoCIS Building, Ground Floor, East Wing',
    category: 'Safety',
    urgency: 'Medium',
    priority: 'MEDIUM',
    status: 'in-progress',
    slaDeadline: hf(50),
    scopeDefinition: {
      description: 'Replace all three broken window panes with toughened safety glass. Board up temporarily pending replacement.',
      estimatedDuration: 5,
      requiredSkills: ['Glazing', 'Carpentry'],
      estimatedCost: 420000,
    },
    assignment: {
      technicianId: 'tech5',
      technicianName: 'Ruth Apio',
      assignedAt: h(24),
      confirmed: true,
    },
    tasks: [
      {
        _id: 't4a',
        title: 'Board up broken windows',
        description: 'Temporarily board up all three window openings for security.',
        status: 'done',
        priority: 'HIGH',
        estimatedDurationDays: 0.5,
        startDate: h(24),
        deadline: h(20),
        completedAt: h(22),
        assigneeId: 'tech5',
        assigneeName: 'Ruth Apio',
        assignedAt: h(24),
        notes: '18mm plywood used. Secured with 50mm screws.',
        createdAt: h(30),
      },
      {
        _id: 't4b',
        title: 'Source and procure safety glass',
        description: 'Source toughened safety glass panels, 1200x900mm x3.',
        status: 'done',
        priority: 'MEDIUM',
        estimatedDurationDays: 1,
        startDate: h(20),
        deadline: h(4),
        completedAt: h(6),
        assigneeId: 'tech5',
        assigneeName: 'Ruth Apio',
        assignedAt: h(24),
        notes: 'Ordered from Kampala Glass & Glazing.',
        createdAt: h(30),
      },
      {
        _id: 't4c',
        title: 'Install replacement window panes',
        description: 'Remove boarding, install new toughened glass panes, seal and finish.',
        status: 'in_progress',
        priority: 'MEDIUM',
        estimatedDurationDays: 1,
        startDate: h(2),
        deadline: hf(22),
        completedAt: null,
        assigneeId: 'tech5',
        assigneeName: 'Ruth Apio',
        assignedAt: h(24),
        notes: null,
        createdAt: h(30),
      },
      {
        _id: 't4d',
        title: 'Security sweep and final inspection',
        description: 'Final walkthrough with security team to confirm all vulnerabilities addressed.',
        status: 'open',
        priority: 'LOW',
        estimatedDurationDays: 2.5,
        startDate: hf(23),
        deadline: hf(83),
        completedAt: null,
        assigneeId: null,
        assigneeName: null,
        assignedAt: null,
        notes: null,
        createdAt: h(30),
      },
    ],
    user: { name: 'Dr. Charles Waiswa', email: 'c.waiswa@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Dr. Charles Waiswa', at: h(48), note: 'Complaint submitted' },
      { action: 'scope_defined', from: 'pending', to: 'scope_defined', byName: 'Estates Officer', at: h(30), note: 'Scope defined' },
      { action: 'assigned', from: 'scope_defined', to: 'assigned', byName: 'Estates Officer', at: h(24), note: 'Assigned to Ruth Apio' },
    ],
    createdAt: h(48),
    updatedAt: h(2),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d4',
    complaintId: 'CMP-005',
    title: 'Air conditioning unit failure — server room',
    description:
      'HVAC unit in the central server room has stopped functioning. Room temperature at 38°C. Multiple servers showing thermal warnings. Risk of hardware failure and data loss.',
    location: 'Administration Block, Server Room 1A',
    category: 'Electrical',
    urgency: 'Critical',
    priority: 'CRITICAL',
    status: 'pending',
    slaDeadline: hf(3),
    tasks: [],
    user: { name: 'Mr. Ivan Kateregga', email: 'i.kateregga@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Mr. Ivan Kateregga', at: h(1), note: 'Complaint submitted' },
    ],
    createdAt: h(1),
    updatedAt: h(1),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d5',
    complaintId: 'CMP-006',
    title: 'Roof leaking into library reading room',
    description:
      'Rain water leaking through roof at two points above the reference section. Water dripping on shelves of rare manuscripts and books. Buckets placed as temporary measure.',
    location: 'Main Library, Reference Section, 2nd Floor',
    category: 'Other',
    urgency: 'High',
    priority: 'HIGH',
    status: 'rework_required',
    slaDeadline: hf(20),
    reworkCount: 1,
    reworkHistory: [
      {
        reworkRound: 1,
        reason: 'INCOMPLETE',
        feedback: 'Initial sealing work only addressed one of the two leak points. Second entry point still active during last night\'s rain.',
        createdAt: h(5),
      },
    ],
    scopeDefinition: {
      description: 'Inspect and repair roof membrane above reference section. Apply waterproof sealant at identified entry points. Inspect guttering.',
      estimatedDuration: 4,
      requiredSkills: ['Roofing', 'Waterproofing'],
      estimatedCost: 1200000,
    },
    assignment: {
      technicianId: 'tech6',
      technicianName: 'Moses Tumwine',
      assignedAt: h(48),
      confirmed: true,
    },
    tasks: [
      {
        _id: 't6a',
        title: 'Emergency temporary waterproofing',
        description: 'Apply temporary roofing tape/membrane to prevent further water ingress.',
        status: 'done',
        priority: 'HIGH',
        estimatedDurationDays: 0.5,
        startDate: h(50),
        deadline: h(46),
        completedAt: h(48),
        assigneeId: 'tech6',
        assigneeName: 'Moses Tumwine',
        assignedAt: h(50),
        notes: 'Covered only entry point 1. Entry point 2 missed.',
        createdAt: h(72),
      },
      {
        _id: 't6b',
        title: 'Full roof membrane inspection and repair',
        description: 'Comprehensive survey of roof membrane, repair all identified defects including entry point 2.',
        status: 'open',
        priority: 'HIGH',
        estimatedDurationDays: 2,
        startDate: hf(2),
        deadline: hf(50),
        completedAt: null,
        assigneeId: 'tech6',
        assigneeName: 'Moses Tumwine',
        assignedAt: h(50),
        notes: null,
        createdAt: h(72),
      },
      {
        _id: 't6c',
        title: 'Guttering inspection and clearance',
        description: 'Clear debris from gutters and downpipes above reference section.',
        status: 'open',
        priority: 'LOW',
        estimatedDurationDays: 1.5,
        startDate: hf(52),
        deadline: hf(88),
        completedAt: null,
        assigneeId: null,
        assigneeName: null,
        assignedAt: null,
        notes: null,
        createdAt: h(72),
      },
    ],
    user: { name: 'Dr. Mary Birungi', email: 'm.birungi@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Dr. Mary Birungi', at: h(72), note: 'Complaint submitted' },
      { action: 'assigned', from: 'scope_defined', to: 'assigned', byName: 'Estates Officer', at: h(48), note: 'Assigned to Moses Tumwine' },
      { action: 'rework_requested', from: 'in-progress', to: 'rework_required', byName: 'Estates Officer', at: h(5), note: 'Rework round 1: INCOMPLETE. Second entry point not addressed.' },
    ],
    createdAt: h(72),
    updatedAt: h(5),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d6',
    complaintId: 'CMP-007',
    title: 'Persistent mold growth in student rooms',
    description:
      'Extensive black mold growth covering walls in rooms 214-218 of Nsibirwa Hall. Students reporting respiratory issues. Health and safety concern.',
    location: 'Nsibirwa Hall, Rooms 214-218',
    category: 'Other',
    urgency: 'Medium',
    priority: 'MEDIUM',
    status: 'pending',
    slaDeadline: hf(96),
    tasks: [],
    user: { name: 'Warden Paul Kirigwajjo', email: 'p.kirigwajjo@mak.ac.ug', role: 'warden' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Warden Paul Kirigwajjo', at: h(12), note: 'Complaint submitted' },
    ],
    createdAt: h(12),
    updatedAt: h(12),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d7',
    complaintId: 'CMP-008',
    title: 'Elevator out of service — accessibility issue',
    description:
      'The elevator in the Faculty of Medicine building has been non-functional for 3 days. Affects students with mobility challenges and staff on upper floors.',
    location: 'Faculty of Medicine Building, Main Elevator',
    category: 'Safety',
    urgency: 'High',
    priority: 'HIGH',
    status: 'escalated',
    slaDeadline: h(-8),
    escalation: {
      status: 'ESCALATED',
      reason: 'BUDGET_EXCEEDED',
      escalatedAt: h(4),
    },
    tasks: [
      {
        _id: 't8a',
        title: 'Initial diagnostic',
        description: 'Certified elevator technician diagnostic assessment.',
        status: 'done',
        priority: 'HIGH',
        estimatedDurationDays: 0.5,
        startDate: h(36),
        deadline: h(34),
        completedAt: h(35),
        assigneeId: 'tech4',
        assigneeName: 'David Ochieng',
        assignedAt: h(36),
        notes: 'Motor controller board failure. Requires specialist replacement part UGX 8.2M.',
        createdAt: h(72),
      },
    ],
    user: { name: 'Prof. Agnes Kibuuka', email: 'a.kibuuka@mak.ac.ug', role: 'resident_staff' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Prof. Agnes Kibuuka', at: h(72), note: 'Complaint submitted' },
      { action: 'escalated', from: 'in-progress', to: 'escalated', byName: 'Estates Officer', at: h(4), note: 'Escalated: BUDGET_EXCEEDED. Repair cost exceeds officer\'s authorization limit.' },
    ],
    scopeDefinition: {
      description: 'Replace motor controller board and run full safety test. Requires certified elevator engineer.',
      estimatedDuration: 3,
      requiredSkills: ['Elevator Maintenance', 'Electrical'],
      estimatedCost: 8200000,
    },
    createdAt: h(72),
    updatedAt: h(4),
  },
  {
    _id: '6756a1b2c3d4e5f6a7b8c9d8',
    complaintId: 'CMP-009',
    title: 'Broken street lights — unsafe campus path',
    description:
      'Five consecutive street lights on the path between the student centre and Mary Stuart Hall are non-functional. Area is completely dark at night.',
    location: 'Main Campus Path, Student Centre to Mary Stuart Hall',
    category: 'Electrical',
    urgency: 'Medium',
    priority: 'MEDIUM',
    status: 'closed',
    slaDeadline: h(-120),
    tasks: [
      {
        _id: 't9a',
        title: 'Replace faulty bulbs and test',
        description: 'Replace all 5 failed lamp units and test circuits.',
        status: 'done',
        priority: 'MEDIUM',
        estimatedDurationDays: 1,
        startDate: h(200),
        deadline: h(176),
        completedAt: h(185),
        assigneeId: 'tech4',
        assigneeName: 'David Ochieng',
        assignedAt: h(200),
        notes: 'LED 150W replacement units installed.',
        createdAt: h(220),
      },
    ],
    user: { name: 'Mr. Robert Asiimwe', email: 'r.asiimwe@mak.ac.ug', role: 'student' },
    history: [
      { action: 'submitted', from: null, to: 'pending', byName: 'Mr. Robert Asiimwe', at: h(220), note: 'Complaint submitted' },
      { action: 'closed', from: 'resolved', to: 'closed', byName: 'Estates Officer', at: h(120), note: 'Closed. SLA Compliant: true' },
    ],
    createdAt: h(220),
    updatedAt: h(120),
  },
];

export const MOCK_STATS = {
  totalComplaints: 9,
  priorityBreakdown: { CRITICAL: 2, HIGH: 4, MEDIUM: 3, LOW: 0 },
  statusBreakdown: { pending: 3, triaged: 1, scope_defined: 1, assigned: 1, 'in-progress': 1, rework_required: 1, escalated: 1, closed: 1 },
  slaBreach: 3,
  avgTimeToResolveHours: 42.5,
};
